name: Run Python Tests with Postgres in Docker

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Wait for Postgres to be ready
      run: |
        echo "Sleeping to ensure DB is ready..."
        sleep 10

    - name: Create schema and seed data
      run: |
        source venv/bin/activate
        python scripts/init_db.py 

    - name: Run Tests
      run: |
        source venv/bin/activate
        python tests/test_question.py